export const mentors = [
  {
    id: "1",
    name: "Dr. Ananya Sharma",
    title: "PhD in Child Psychology, IIT Delhi",
    avatar:
      "https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 4.9,
    reviews: 128,
    experience: 12,
    subjects: ["Mathematics", "Science", "Concept-Based Learning"],
    focusAreas: [
      "Confidence Building",
      "Concept-Based Learning",
      "Homework Support",
    ],
    languages: ["English", "Hindi"],
    hourlyRate: 800,
    location: "Mumbai, Online",
    bio: "I believe every child has a unique learning style. My approach combines academic rigor with emotional intelligence to help children not just score better, but think better.",
    education: [
      {
        degree: "PhD in Child Psychology",
        institution: "IIT Delhi",
        year: "2015",
      },
      {
        degree: "M.Sc in Mathematics",
        institution: "Delhi University",
        year: "2010",
      },
    ],
    achievements: [
      "Helped 200+ students improve grades by 30% in 6 months",
      "Featured in Education Today magazine",
      "Certified child counselor with 12+ years experience",
    ],
    availability: ["Mon", "Wed", "Fri"],
    verified: true,
    featured: true,
  },
  {
    id: "2",
    name: "Rajesh Kumar",
    title: "M.Tech, IIT Bombay — Academic Coach",
    avatar:
      "https://images.pexels.com/photos/6148101/pexels-photo-6148101.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 4.8,
    reviews: 94,
    experience: 8,
    subjects: ["Physics", "Mathematics", "JEE Prep"],
    focusAreas: ["Discipline", "Habit Building", "Speaking Skills"],
    languages: ["English", "Hindi", "Tamil"],
    hourlyRate: 600,
    location: "Bangalore, Online",
    bio: "Academic excellence is a byproduct of good habits. I mentor students to build discipline and curiosity that lasts a lifetime.",
    education: [
      {
        degree: "M.Tech in Aerospace Engineering",
        institution: "IIT Bombay",
        year: "2016",
      },
      {
        degree: "B.Tech in Mechanical Engineering",
        institution: "Anna University",
        year: "2013",
      },
    ],
    achievements: [
      "Mentored 50+ JEE qualifiers",
      "Created habit-tracking system used by 1000+ students",
      "TEDx speaker on student discipline",
    ],
    availability: ["Tue", "Thu", "Sat"],
    verified: true,
    featured: true,
  },
  {
    id: "3",
    name: "Priya Nair",
    title: "MA in Communication, NID Ahmedabad",
    avatar:
      "https://images.pexels.com/photos/3760263/pexels-photo-3760263.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 5.0,
    reviews: 67,
    experience: 6,
    subjects: ["English", "Social Studies", "Public Speaking"],
    focusAreas: ["Communication", "Speaking Skills", "Confidence Building"],
    languages: ["English", "Malayalam", "Hindi"],
    hourlyRate: 500,
    location: "Kochi, Online",
    bio: "Communication is the bridge between knowledge and expression. I help children find their voice and use it with confidence.",
    education: [
      {
        degree: "MA in Communication Design",
        institution: "NID Ahmedabad",
        year: "2018",
      },
      {
        degree: "BA in English Literature",
        institution: "University of Kerala",
        year: "2015",
      },
    ],
    achievements: [
      "Coached 80+ students to win state-level debates",
      "Designed communication curriculum for 3 schools",
      "Certified public speaking trainer",
    ],
    availability: ["Mon", "Tue", "Thu"],
    verified: true,
    featured: false,
  },
  {
    id: "4",
    name: "Vikram Mehta",
    title: "B.Tech IIT Delhi — STEM Specialist",
    avatar:
      "https://images.pexels.com/photos/8198052/pexels-photo-8198052.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 4.7,
    reviews: 112,
    experience: 10,
    subjects: ["Mathematics", "Physics", "Computer Science"],
    focusAreas: ["Concept-Based Learning", "Homework Support", "Discipline"],
    languages: ["English", "Gujarati", "Hindi"],
    hourlyRate: 700,
    location: "Ahmedabad, Online",
    bio: 'I make STEM intuitive. When a child understands the "why" behind a concept, the "what" follows naturally.',
    education: [
      {
        degree: "B.Tech in Computer Science",
        institution: "IIT Delhi",
        year: "2014",
      },
    ],
    achievements: [
      "Mentored 300+ students in STEM subjects",
      "Developed visual learning modules for physics",
      "Top-rated mentor on 3 platforms",
    ],
    availability: ["Wed", "Fri", "Sun"],
    verified: true,
    featured: false,
  },
  {
    id: "5",
    name: "Sneha Reddy",
    title: "M.Ed, Osmania University — Child Development Expert",
    avatar:
      "https://images.pexels.com/photos/5905858/pexels-photo-5905858.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 4.9,
    reviews: 85,
    experience: 9,
    subjects: ["All Subjects (Primary)", "Hindi", "Telugu"],
    focusAreas: ["Habit Building", "Confidence Building", "Homework Support"],
    languages: ["English", "Telugu", "Hindi"],
    hourlyRate: 450,
    location: "Hyderabad, Online",
    bio: "Primary years are the foundation of a child's entire academic journey. I make learning joyful and habits sustainable.",
    education: [
      {
        degree: "M.Ed in Early Childhood Education",
        institution: "Osmania University",
        year: "2015",
      },
      { degree: "B.Ed", institution: "Osmania University", year: "2013" },
    ],
    achievements: [
      "Specialized in primary school mentorship",
      "Created a habit-formation framework for kids 6-10",
      "Parent satisfaction rate of 98%",
    ],
    availability: ["Mon", "Wed", "Fri", "Sat"],
    verified: true,
    featured: true,
  },
  {
    id: "6",
    name: "Arjun Gupta",
    title: "MBA IIM Bangalore — Life Skills Coach",
    avatar:
      "https://images.pexels.com/photos/8439093/pexels-photo-8439093.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 4.6,
    reviews: 43,
    experience: 5,
    subjects: ["Life Skills", "Personality Development", "Career Guidance"],
    focusAreas: [
      "Communication",
      "Discipline",
      "Speaking Skills",
      "Confidence Building",
    ],
    languages: ["English", "Hindi"],
    hourlyRate: 650,
    location: "Pune, Online",
    bio: "Academic success is just one part of life. I help children develop the soft skills that determine long-term success.",
    education: [
      { degree: "MBA", institution: "IIM Bangalore", year: "2019" },
      { degree: "B.Tech in IT", institution: "BITS Pilani", year: "2016" },
    ],
    achievements: [
      "Conducted 100+ personality development workshops",
      "Mentored students from 15+ schools",
      "Certified life coach (ICF)",
    ],
    availability: ["Tue", "Thu", "Sat"],
    verified: true,
    featured: false,
  },
];

export const focusAreas = [
  "Academic Tutoring",
  "Confidence Building",
  "Communication",
  "Discipline",
  "Habit Building",
  "Speaking Skills",
  "Homework Support",
  "Concept-Based Learning",
  "Child Development Mentoring",
];

export const subjects = [
  "Mathematics",
  "Science",
  "Physics",
  "Chemistry",
  "Biology",
  "English",
  "Social Studies",
  "Computer Science",
  "Hindi",
  "Telugu",
  "Tamil",
  "Public Speaking",
  "Life Skills",
];

export const parentDashboardData = {
  children: [
    {
      id: "c1",
      name: "Aarav Singh",
      grade: "Class 8",
      avatar:
        "https://images.pexels.com/photos/8422535/pexels-photo-8422535.jpeg?auto=compress&cs=tinysrgb&w=200",
      assignedMentor: "Dr. Ananya Sharma",
      mentorId: "1",
      progress: 72,
      upcomingSession: "Tomorrow, 4:00 PM",
      recentActivity: [
        {
          subject: "Mathematics",
          topic: "Linear Equations",
          score: "85%",
          date: "2026-09-18",
        },
        {
          subject: "Science",
          topic: "Photosynthesis",
          score: "92%",
          date: "2026-09-16",
        },
        {
          subject: "Mathematics",
          topic: "Geometry Basics",
          score: "78%",
          date: "2026-09-14",
        },
      ],
      skillsProgress: [
        { skill: "Academic Performance", value: 78 },
        { skill: "Confidence", value: 65 },
        { skill: "Communication", value: 70 },
        { skill: "Discipline", value: 82 },
        { skill: "Speaking Skills", value: 60 },
      ],
    },
    {
      id: "c2",
      name: "Diya Singh",
      grade: "Class 5",
      avatar:
        "https://images.pexels.com/photos/8422533/pexels-photo-8422533.jpeg?auto=compress&cs=tinysrgb&w=200",
      assignedMentor: "Sneha Reddy",
      mentorId: "5",
      progress: 85,
      upcomingSession: "Today, 5:30 PM",
      recentActivity: [
        {
          subject: "English",
          topic: "Story Writing",
          score: "88%",
          date: "2026-09-19",
        },
        {
          subject: "Mathematics",
          topic: "Multiplication",
          score: "95%",
          date: "2026-09-17",
        },
        {
          subject: "EVS",
          topic: "Plants & Animals",
          score: "90%",
          date: "2026-09-15",
        },
      ],
      skillsProgress: [
        { skill: "Academic Performance", value: 88 },
        { skill: "Confidence", value: 80 },
        { skill: "Communication", value: 75 },
        { skill: "Discipline", value: 90 },
        { skill: "Speaking Skills", value: 70 },
      ],
    },
  ],
  upcomingSessions: [
    {
      id: "s1",
      childName: "Diya Singh",
      mentorName: "Sneha Reddy",
      date: "Today",
      time: "5:30 PM",
      subject: "English",
    },
    {
      id: "s2",
      childName: "Aarav Singh",
      mentorName: "Dr. Ananya Sharma",
      date: "Tomorrow",
      time: "4:00 PM",
      subject: "Mathematics",
    },
    {
      id: "s3",
      childName: "Aarav Singh",
      mentorName: "Dr. Ananya Sharma",
      date: "Mon, Sep 23",
      time: "4:00 PM",
      subject: "Science",
    },
  ],
  monthlyReport: {
    totalSessions: 12,
    hoursSpent: 18,
    averageScore: "85%",
    improvement: "+12%",
  },
};

export const mentorDashboardData = {
  stats: {
    totalStudents: 24,
    upcomingSessions: 8,
    monthlyEarnings: 48000,
    rating: 4.9,
  },
  upcomingSessions: [
    {
      id: "ms1",
      studentName: "Aarav Singh",
      date: "Tomorrow",
      time: "4:00 PM",
      subject: "Mathematics",
      parentName: "Rohit Singh",
    },
    {
      id: "ms2",
      studentName: "Ira Patel",
      date: "Tomorrow",
      time: "6:00 PM",
      subject: "Science",
      parentName: "Meera Patel",
    },
    {
      id: "ms3",
      studentName: "Kabir Joshi",
      date: "Mon, Sep 23",
      time: "5:00 PM",
      subject: "Mathematics",
      parentName: "Anil Joshi",
    },
    {
      id: "ms4",
      studentName: "Sara Khan",
      date: "Tue, Sep 24",
      time: "3:30 PM",
      subject: "Concept-Based Learning",
      parentName: "Fatima Khan",
    },
  ],
  students: [
    {
      id: "st1",
      name: "Aarav Singh",
      grade: "Class 8",
      progress: 72,
      parentName: "Rohit Singh",
      avatar:
        "https://images.pexels.com/photos/8422535/pexels-photo-8422535.jpeg?auto=compress&cs=tinysrgb&w=200",
    },
    {
      id: "st2",
      name: "Ira Patel",
      grade: "Class 7",
      progress: 85,
      parentName: "Meera Patel",
      avatar:
        "https://images.pexels.com/photos/8422535/pexels-photo-8422535.jpeg?auto=compress&cs=tinysrgb&w=200",
    },
    {
      id: "st3",
      name: "Kabir Joshi",
      grade: "Class 9",
      progress: 68,
      parentName: "Anil Joshi",
      avatar:
        "https://images.pexels.com/photos/8422535/pexels-photo-8422535.jpeg?auto=compress&cs=tinysrgb&w=200",
    },
    {
      id: "st4",
      name: "Sara Khan",
      grade: "Class 6",
      progress: 91,
      parentName: "Fatima Khan",
      avatar:
        "https://images.pexels.com/photos/8422535/pexels-photo-8422535.jpeg?auto=compress&cs=tinysrgb&w=200",
    },
  ],
  earnings: [
    { month: "Apr", amount: 32000 },
    { month: "May", amount: 38000 },
    { month: "Jun", amount: 35000 },
    { month: "Jul", amount: 42000 },
    { month: "Aug", amount: 45000 },
    { month: "Sep", amount: 48000 },
  ],
};
